// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/descredit/descredit.proto

package descredit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	DB "github.com/pkt-cash/pktd/lnd/lnrpc/protos/DB"
	_ "github.com/pkt-cash/pktd/lnd/lnrpc/protos/lock"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DuplicateBlock 2 identical blocks were generated (Updated the structure)
type DuplicateBlock struct {
	// first_block_header — copied block
	/// Caleb: Should be `message Block` rather than string
	FirstBlockHeader *DB.Block `protobuf:"bytes,1,opt,name=first_block_header,json=firstBlockHeader,proto3" json:"first_block_header,omitempty"`
	// second_block_header — block copy
	/// Caleb: Should be `message Block` rather than string
	SecondBlockHeader    *DB.Block `protobuf:"bytes,2,opt,name=second_block_header,json=secondBlockHeader,proto3" json:"second_block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DuplicateBlock) Reset()         { *m = DuplicateBlock{} }
func (m *DuplicateBlock) String() string { return proto.CompactTextString(m) }
func (*DuplicateBlock) ProtoMessage()    {}
func (*DuplicateBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1aba1ea580c354, []int{0}
}

func (m *DuplicateBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateBlock.Unmarshal(m, b)
}
func (m *DuplicateBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateBlock.Marshal(b, m, deterministic)
}
func (m *DuplicateBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateBlock.Merge(m, src)
}
func (m *DuplicateBlock) XXX_Size() int {
	return xxx_messageInfo_DuplicateBlock.Size(m)
}
func (m *DuplicateBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateBlock.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateBlock proto.InternalMessageInfo

func (m *DuplicateBlock) GetFirstBlockHeader() *DB.Block {
	if m != nil {
		return m.FirstBlockHeader
	}
	return nil
}

func (m *DuplicateBlock) GetSecondBlockHeader() *DB.Block {
	if m != nil {
		return m.SecondBlockHeader
	}
	return nil
}

// DenialService the issuer accepts a lock_tokens request from a sender but
// then ignores the transfer_tokens request from the recipient
type DenialService struct {
	// lock — hash of ignored lock
	Lock string `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	// htlc_secret_hash — htlc genereted issuer
	HtlcSecretHash string `protobuf:"bytes,2,opt,name=htlc_secret_hash,json=htlcSecretHash,proto3" json:"htlc_secret_hash,omitempty"`
	// proof_mercle_branch — proof from PKT blockchain
	ProofMercleBranch    string   `protobuf:"bytes,3,opt,name=proof_mercle_branch,json=proofMercleBranch,proto3" json:"proof_mercle_branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenialService) Reset()         { *m = DenialService{} }
func (m *DenialService) String() string { return proto.CompactTextString(m) }
func (*DenialService) ProtoMessage()    {}
func (*DenialService) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1aba1ea580c354, []int{1}
}

func (m *DenialService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenialService.Unmarshal(m, b)
}
func (m *DenialService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenialService.Marshal(b, m, deterministic)
}
func (m *DenialService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenialService.Merge(m, src)
}
func (m *DenialService) XXX_Size() int {
	return xxx_messageInfo_DenialService.Size(m)
}
func (m *DenialService) XXX_DiscardUnknown() {
	xxx_messageInfo_DenialService.DiscardUnknown(m)
}

var xxx_messageInfo_DenialService proto.InternalMessageInfo

func (m *DenialService) GetLock() string {
	if m != nil {
		return m.Lock
	}
	return ""
}

func (m *DenialService) GetHtlcSecretHash() string {
	if m != nil {
		return m.HtlcSecretHash
	}
	return ""
}

func (m *DenialService) GetProofMercleBranch() string {
	if m != nil {
		return m.ProofMercleBranch
	}
	return ""
}

func init() {
	proto.RegisterType((*DuplicateBlock)(nil), "descredit.DuplicateBlock")
	proto.RegisterType((*DenialService)(nil), "descredit.DenialService")
}

func init() { proto.RegisterFile("protos/descredit/descredit.proto", fileDescriptor_4d1aba1ea580c354) }

var fileDescriptor_4d1aba1ea580c354 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbd, 0x6a, 0xf3, 0x30,
	0x14, 0x86, 0xc9, 0xf7, 0x95, 0x42, 0x54, 0x6a, 0x12, 0x05, 0xda, 0x90, 0x29, 0x64, 0xca, 0x52,
	0x1b, 0x1a, 0xba, 0x95, 0x0e, 0xc6, 0x43, 0x96, 0x2e, 0xce, 0xd6, 0x45, 0xc8, 0x47, 0x27, 0x95,
	0xb0, 0x62, 0x19, 0x49, 0xe9, 0xd6, 0x5b, 0xe8, 0x35, 0x17, 0x1d, 0xa7, 0xbf, 0x74, 0xb0, 0x79,
	0xf5, 0x3e, 0xcf, 0x91, 0x04, 0x62, 0xcb, 0xde, 0xbb, 0xe8, 0x42, 0xa1, 0x30, 0x80, 0x47, 0x65,
	0xe2, 0x57, 0xca, 0x09, 0xf1, 0xf1, 0x67, 0xb1, 0xb8, 0x3e, 0xc9, 0x55, 0x59, 0x44, 0xd7, 0x62,
	0xa7, 0x9a, 0xc1, 0x59, 0x5c, 0x9d, 0x80, 0x75, 0xd0, 0xd2, 0x6f, 0xe8, 0x57, 0x6f, 0x23, 0x96,
	0x55, 0xc7, 0xde, 0x1a, 0x90, 0x11, 0xcb, 0x04, 0xf8, 0x3d, 0xe3, 0x7b, 0xe3, 0x43, 0x14, 0x4d,
	0x5a, 0x0a, 0x8d, 0x52, 0xa1, 0x9f, 0x8f, 0x96, 0xa3, 0xf5, 0xc5, 0x6d, 0x96, 0x7f, 0x6c, 0x4b,
	0x6e, 0x3d, 0x21, 0x93, 0xf2, 0x96, 0x3c, 0xfe, 0xc0, 0x66, 0x01, 0xc1, 0x75, 0xea, 0xe7, 0xf8,
	0xbf, 0x3f, 0xc7, 0xa7, 0x83, 0xfa, 0x6d, 0x7e, 0xf5, 0xca, 0x2e, 0x2b, 0xec, 0x8c, 0xb4, 0x3b,
	0xf4, 0x2f, 0x06, 0x90, 0x73, 0x76, 0x96, 0x30, 0x5d, 0x60, 0x5c, 0x53, 0xe6, 0x6b, 0x36, 0xd1,
	0xd1, 0x82, 0x08, 0x08, 0x1e, 0xa3, 0xd0, 0x32, 0x68, 0x3a, 0x61, 0x5c, 0x67, 0xa9, 0xdf, 0x51,
	0xbd, 0x95, 0x41, 0xf3, 0x9c, 0xcd, 0x7a, 0xef, 0xdc, 0x5e, 0x1c, 0xd0, 0x83, 0x45, 0xd1, 0x78,
	0xd9, 0x81, 0x9e, 0xff, 0x27, 0x79, 0x4a, 0xe8, 0x91, 0x48, 0x49, 0xa0, 0xbc, 0x7b, 0xda, 0x3c,
	0x9b, 0xa8, 0x8f, 0x4d, 0x0e, 0xee, 0x50, 0xf4, 0x6d, 0xbc, 0x01, 0x19, 0x74, 0x0a, 0xaa, 0xb0,
	0x5d, 0xfa, 0x7c, 0x0f, 0xc5, 0xef, 0x27, 0x69, 0xce, 0xa9, 0xd9, 0xbc, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0x63, 0x11, 0x28, 0xad, 0x01, 0x00, 0x00,
}
