// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/replicator/replicator.proto

package replicator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	DB "github.com/pkt-cash/pktd/lnd/lnrpc/protos/DB"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTokenOffersRequest struct {
	IssuerId             string      `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Params               *Pagination `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTokenOffersRequest) Reset()         { *m = GetTokenOffersRequest{} }
func (m *GetTokenOffersRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenOffersRequest) ProtoMessage()    {}
func (*GetTokenOffersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{0}
}

func (m *GetTokenOffersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenOffersRequest.Unmarshal(m, b)
}
func (m *GetTokenOffersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenOffersRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenOffersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenOffersRequest.Merge(m, src)
}
func (m *GetTokenOffersRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenOffersRequest.Size(m)
}
func (m *GetTokenOffersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenOffersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenOffersRequest proto.InternalMessageInfo

func (m *GetTokenOffersRequest) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *GetTokenOffersRequest) GetParams() *Pagination {
	if m != nil {
		return m.Params
	}
	return nil
}

type GetTokenOffersResponse struct {
	Offers               []*TokenOffer `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	Total                uint64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetTokenOffersResponse) Reset()         { *m = GetTokenOffersResponse{} }
func (m *GetTokenOffersResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenOffersResponse) ProtoMessage()    {}
func (*GetTokenOffersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{1}
}

func (m *GetTokenOffersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenOffersResponse.Unmarshal(m, b)
}
func (m *GetTokenOffersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenOffersResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenOffersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenOffersResponse.Merge(m, src)
}
func (m *GetTokenOffersResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenOffersResponse.Size(m)
}
func (m *GetTokenOffersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenOffersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenOffersResponse proto.InternalMessageInfo

func (m *GetTokenOffersResponse) GetOffers() []*TokenOffer {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *GetTokenOffersResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// GetTokenListRequest — request token list with pagination
type GetTokenListRequest struct {
	// issuer_id is user login issued this token
	IssuerId string `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	// params of paginaton
	Params               *Pagination `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTokenListRequest) Reset()         { *m = GetTokenListRequest{} }
func (m *GetTokenListRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenListRequest) ProtoMessage()    {}
func (*GetTokenListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{2}
}

func (m *GetTokenListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenListRequest.Unmarshal(m, b)
}
func (m *GetTokenListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenListRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenListRequest.Merge(m, src)
}
func (m *GetTokenListRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenListRequest.Size(m)
}
func (m *GetTokenListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenListRequest proto.InternalMessageInfo

func (m *GetTokenListRequest) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *GetTokenListRequest) GetParams() *Pagination {
	if m != nil {
		return m.Params
	}
	return nil
}

// GetTokenListResponse — list of tokens with additional info
type GetTokenListResponse struct {
	// tokens list of registred tokens
	Tokens []*Token `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// total number of registered tokens, if the issued_id is passed, only
	// its tokens are taken into account
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenListResponse) Reset()         { *m = GetTokenListResponse{} }
func (m *GetTokenListResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenListResponse) ProtoMessage()    {}
func (*GetTokenListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{3}
}

func (m *GetTokenListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenListResponse.Unmarshal(m, b)
}
func (m *GetTokenListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenListResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenListResponse.Merge(m, src)
}
func (m *GetTokenListResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenListResponse.Size(m)
}
func (m *GetTokenListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenListResponse proto.InternalMessageInfo

func (m *GetTokenListResponse) GetTokens() []*Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *GetTokenListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Token struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// offer on token issue
	Token                *DB.Token `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Root                 string    `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Token) GetToken() *DB.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Token) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

type TokenOffer struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// TODO: discuss
	//  ? Should we assume decimal prices
	//  ? Add units field
	Price      uint64      `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	IssuerInfo *IssuerInfo `protobuf:"bytes,3,opt,name=issuer_info,json=issuerInfo,proto3" json:"issuer_info,omitempty"`
	// It is assumed that the each registered token holder login is unique
	//
	// Value of this field may be empty orRegisterTokenHolder filled depending
	// on context (e.g. gettokenoffers, verifytokenpurchasesignature)
	TokenHolderLogin string `protobuf:"bytes,4,opt,name=token_holder_login,json=tokenHolderLogin,proto3" json:"token_holder_login,omitempty"`
	// It is assumed that the each registered token holder login is unique
	//
	// Value of this field may be empty or filled depending on context
	// (e.g. gettokenoffers, verifytokenpurchasesignature)
	TokenBuyerLogin string `protobuf:"bytes,5,opt,name=token_buyer_login,json=tokenBuyerLogin,proto3" json:"token_buyer_login,omitempty"`
	// This field protects issuers from such a case, when potential buyer
	// successfully acquires dozens of signatures just in case if that issuer
	// would raise up the price later. If a Token Wallet holder would like to
	// open channel with an outdated offer, Replicator would reject to register
	// this purchase and buyer stays unprotected
	ValidUntilSeconds int64 `protobuf:"varint,6,opt,name=valid_until_seconds,json=validUntilSeconds,proto3" json:"valid_until_seconds,omitempty"`
	// count — the number of tokens to be issued
	Count                uint64   `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenOffer) Reset()         { *m = TokenOffer{} }
func (m *TokenOffer) String() string { return proto.CompactTextString(m) }
func (*TokenOffer) ProtoMessage()    {}
func (*TokenOffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{5}
}

func (m *TokenOffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenOffer.Unmarshal(m, b)
}
func (m *TokenOffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenOffer.Marshal(b, m, deterministic)
}
func (m *TokenOffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenOffer.Merge(m, src)
}
func (m *TokenOffer) XXX_Size() int {
	return xxx_messageInfo_TokenOffer.Size(m)
}
func (m *TokenOffer) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenOffer.DiscardUnknown(m)
}

var xxx_messageInfo_TokenOffer proto.InternalMessageInfo

func (m *TokenOffer) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenOffer) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TokenOffer) GetIssuerInfo() *IssuerInfo {
	if m != nil {
		return m.IssuerInfo
	}
	return nil
}

func (m *TokenOffer) GetTokenHolderLogin() string {
	if m != nil {
		return m.TokenHolderLogin
	}
	return ""
}

func (m *TokenOffer) GetTokenBuyerLogin() string {
	if m != nil {
		return m.TokenBuyerLogin
	}
	return ""
}

func (m *TokenOffer) GetValidUntilSeconds() int64 {
	if m != nil {
		return m.ValidUntilSeconds
	}
	return 0
}

func (m *TokenOffer) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IssuerInfo struct {
	// This value is explicetely used by Replicator to uniquely identify related
	// issuer later in order to ban him (discredite case), since
	// "identity_pubkey", "host" may be changed
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The following field values are used to open payment channel, invoices
	// commands execution etc.
	IdentityPubkey string `protobuf:"bytes,2,opt,name=identity_pubkey,json=identityPubkey,proto3" json:"identity_pubkey,omitempty"`
	// Is used to establish client connection to the issuer's node during some
	// RPC calls
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuerInfo) Reset()         { *m = IssuerInfo{} }
func (m *IssuerInfo) String() string { return proto.CompactTextString(m) }
func (*IssuerInfo) ProtoMessage()    {}
func (*IssuerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{6}
}

func (m *IssuerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuerInfo.Unmarshal(m, b)
}
func (m *IssuerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuerInfo.Marshal(b, m, deterministic)
}
func (m *IssuerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuerInfo.Merge(m, src)
}
func (m *IssuerInfo) XXX_Size() int {
	return xxx_messageInfo_IssuerInfo.Size(m)
}
func (m *IssuerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IssuerInfo proto.InternalMessageInfo

func (m *IssuerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IssuerInfo) GetIdentityPubkey() string {
	if m != nil {
		return m.IdentityPubkey
	}
	return ""
}

func (m *IssuerInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

// NOTE: we don't provide any token holder identification since the reqeuest is
// authorized with JWT applied to the request metadata. It means, that
// replicator is capable to extract all data needed to process the request
type GetTokenBalancesRequest struct {
	Params               *Pagination `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTokenBalancesRequest) Reset()         { *m = GetTokenBalancesRequest{} }
func (m *GetTokenBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenBalancesRequest) ProtoMessage()    {}
func (*GetTokenBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{7}
}

func (m *GetTokenBalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenBalancesRequest.Unmarshal(m, b)
}
func (m *GetTokenBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenBalancesRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenBalancesRequest.Merge(m, src)
}
func (m *GetTokenBalancesRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenBalancesRequest.Size(m)
}
func (m *GetTokenBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenBalancesRequest proto.InternalMessageInfo

func (m *GetTokenBalancesRequest) GetParams() *Pagination {
	if m != nil {
		return m.Params
	}
	return nil
}

type GetTokenBalancesResponse struct {
	Balances             []*TokenBalance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	Total                uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTokenBalancesResponse) Reset()         { *m = GetTokenBalancesResponse{} }
func (m *GetTokenBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenBalancesResponse) ProtoMessage()    {}
func (*GetTokenBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{8}
}

func (m *GetTokenBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenBalancesResponse.Unmarshal(m, b)
}
func (m *GetTokenBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenBalancesResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenBalancesResponse.Merge(m, src)
}
func (m *GetTokenBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenBalancesResponse.Size(m)
}
func (m *GetTokenBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenBalancesResponse proto.InternalMessageInfo

func (m *GetTokenBalancesResponse) GetBalances() []*TokenBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *GetTokenBalancesResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type TokenBalance struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Available            uint64   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Frozen               uint64   `protobuf:"varint,3,opt,name=frozen,proto3" json:"frozen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenBalance) Reset()         { *m = TokenBalance{} }
func (m *TokenBalance) String() string { return proto.CompactTextString(m) }
func (*TokenBalance) ProtoMessage()    {}
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{9}
}

func (m *TokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBalance.Unmarshal(m, b)
}
func (m *TokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBalance.Marshal(b, m, deterministic)
}
func (m *TokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBalance.Merge(m, src)
}
func (m *TokenBalance) XXX_Size() int {
	return xxx_messageInfo_TokenBalance.Size(m)
}
func (m *TokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBalance proto.InternalMessageInfo

func (m *TokenBalance) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenBalance) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *TokenBalance) GetFrozen() uint64 {
	if m != nil {
		return m.Frozen
	}
	return 0
}

type Pagination struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{10}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type VerifyIssuerRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyIssuerRequest) Reset()         { *m = VerifyIssuerRequest{} }
func (m *VerifyIssuerRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyIssuerRequest) ProtoMessage()    {}
func (*VerifyIssuerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{11}
}

func (m *VerifyIssuerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyIssuerRequest.Unmarshal(m, b)
}
func (m *VerifyIssuerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyIssuerRequest.Marshal(b, m, deterministic)
}
func (m *VerifyIssuerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyIssuerRequest.Merge(m, src)
}
func (m *VerifyIssuerRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyIssuerRequest.Size(m)
}
func (m *VerifyIssuerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyIssuerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyIssuerRequest proto.InternalMessageInfo

func (m *VerifyIssuerRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

// IssueTokenRequest — info about token will be issued
type IssueTokenRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// offer on token issue
	Offer                *DB.Token `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IssueTokenRequest) Reset()         { *m = IssueTokenRequest{} }
func (m *IssueTokenRequest) String() string { return proto.CompactTextString(m) }
func (*IssueTokenRequest) ProtoMessage()    {}
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{12}
}

func (m *IssueTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokenRequest.Unmarshal(m, b)
}
func (m *IssueTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokenRequest.Marshal(b, m, deterministic)
}
func (m *IssueTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokenRequest.Merge(m, src)
}
func (m *IssueTokenRequest) XXX_Size() int {
	return xxx_messageInfo_IssueTokenRequest.Size(m)
}
func (m *IssueTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokenRequest proto.InternalMessageInfo

func (m *IssueTokenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IssueTokenRequest) GetOffer() *DB.Token {
	if m != nil {
		return m.Offer
	}
	return nil
}

type SaveBlockRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Block                *DB.Block `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SaveBlockRequest) Reset()         { *m = SaveBlockRequest{} }
func (m *SaveBlockRequest) String() string { return proto.CompactTextString(m) }
func (*SaveBlockRequest) ProtoMessage()    {}
func (*SaveBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{13}
}

func (m *SaveBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveBlockRequest.Unmarshal(m, b)
}
func (m *SaveBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveBlockRequest.Marshal(b, m, deterministic)
}
func (m *SaveBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveBlockRequest.Merge(m, src)
}
func (m *SaveBlockRequest) XXX_Size() int {
	return xxx_messageInfo_SaveBlockRequest.Size(m)
}
func (m *SaveBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveBlockRequest proto.InternalMessageInfo

func (m *SaveBlockRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveBlockRequest) GetBlock() *DB.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetTokenRequest struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{14}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

type GetTokenResponse struct {
	Tokens               *Token   `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f15fabe54a973d, []int{15}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetTokens() *Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTokenOffersRequest)(nil), "replicator.GetTokenOffersRequest")
	proto.RegisterType((*GetTokenOffersResponse)(nil), "replicator.GetTokenOffersResponse")
	proto.RegisterType((*GetTokenListRequest)(nil), "replicator.GetTokenListRequest")
	proto.RegisterType((*GetTokenListResponse)(nil), "replicator.GetTokenListResponse")
	proto.RegisterType((*Token)(nil), "replicator.Token")
	proto.RegisterType((*TokenOffer)(nil), "replicator.TokenOffer")
	proto.RegisterType((*IssuerInfo)(nil), "replicator.IssuerInfo")
	proto.RegisterType((*GetTokenBalancesRequest)(nil), "replicator.GetTokenBalancesRequest")
	proto.RegisterType((*GetTokenBalancesResponse)(nil), "replicator.GetTokenBalancesResponse")
	proto.RegisterType((*TokenBalance)(nil), "replicator.TokenBalance")
	proto.RegisterType((*Pagination)(nil), "replicator.Pagination")
	proto.RegisterType((*VerifyIssuerRequest)(nil), "replicator.VerifyIssuerRequest")
	proto.RegisterType((*IssueTokenRequest)(nil), "replicator.IssueTokenRequest")
	proto.RegisterType((*SaveBlockRequest)(nil), "replicator.SaveBlockRequest")
	proto.RegisterType((*GetTokenRequest)(nil), "replicator.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "replicator.GetTokenResponse")
}

func init() {
	proto.RegisterFile("protos/replicator/replicator.proto", fileDescriptor_f2f15fabe54a973d)
}

var fileDescriptor_f2f15fabe54a973d = []byte{
	// 830 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0x56, 0xd2, 0x24, 0x97, 0xcc, 0x55, 0x69, 0xb3, 0x2d, 0x39, 0x93, 0x16, 0x11, 0xcc, 0x49,
	0x14, 0x38, 0x1c, 0xe9, 0xa8, 0x40, 0x42, 0xe2, 0x03, 0x81, 0xaa, 0x44, 0x2a, 0xa2, 0xb8, 0x94,
	0x8a, 0x4a, 0x10, 0xf9, 0x65, 0x9d, 0xac, 0xe2, 0xec, 0x1a, 0x7b, 0x5d, 0x29, 0xfc, 0x0b, 0x7e,
	0x09, 0x7f, 0x11, 0xed, 0x9b, 0xed, 0xbc, 0x15, 0xbe, 0xf0, 0x21, 0xd2, 0xce, 0xcc, 0x33, 0x8f,
	0x67, 0x66, 0x9f, 0xdd, 0x0d, 0xd8, 0x49, 0xca, 0x38, 0xcb, 0x46, 0x29, 0x4e, 0x62, 0x12, 0x78,
	0x9c, 0xa5, 0x95, 0xa5, 0x23, 0x83, 0x08, 0x4a, 0xcf, 0xe0, 0x95, 0xc6, 0x7f, 0x37, 0x1e, 0x71,
	0xb6, 0xc0, 0x34, 0xf4, 0x15, 0x68, 0x70, 0x36, 0x63, 0x6c, 0x16, 0xe3, 0x91, 0xb4, 0xfc, 0x3c,
	0x1a, 0xe1, 0x65, 0xc2, 0x57, 0x2a, 0x68, 0x87, 0xf0, 0xce, 0x35, 0xe6, 0x3f, 0x8b, 0x84, 0x1f,
	0xa3, 0x08, 0xa7, 0x99, 0x8b, 0xff, 0xc8, 0x71, 0xc6, 0xd1, 0x19, 0x74, 0x48, 0x96, 0xe5, 0x38,
	0x9d, 0x92, 0xd0, 0xaa, 0x0d, 0x6b, 0x17, 0x1d, 0xb7, 0xad, 0x1c, 0x93, 0x10, 0x39, 0xd0, 0x4a,
	0xbc, 0xd4, 0x5b, 0x66, 0x56, 0x7d, 0x58, 0xbb, 0x78, 0xf9, 0xb6, 0xef, 0x54, 0x4a, 0xbb, 0xf5,
	0x66, 0x84, 0x7a, 0x9c, 0x30, 0xea, 0x6a, 0x94, 0xfd, 0x3b, 0xf4, 0x37, 0xbf, 0x92, 0x25, 0x8c,
	0x66, 0x58, 0x30, 0x31, 0xe9, 0xb1, 0x6a, 0xc3, 0x83, 0x4d, 0xa6, 0x32, 0xc1, 0xd5, 0x28, 0x74,
	0x0a, 0x4d, 0xce, 0xb8, 0x17, 0xcb, 0x0f, 0x37, 0x5c, 0x65, 0xd8, 0x3e, 0x9c, 0x18, 0xfe, 0x1b,
	0x92, 0xf1, 0xff, 0xa5, 0x87, 0x07, 0x38, 0x5d, 0xff, 0x86, 0xee, 0xe0, 0x63, 0x68, 0xc9, 0x79,
	0x9b, 0x0e, 0x7a, 0x5b, 0x1d, 0xb8, 0x1a, 0xb0, 0x5e, 0x7c, 0xd3, 0x14, 0x7f, 0x0f, 0x4d, 0x09,
	0x43, 0x08, 0x1a, 0xd4, 0x5b, 0x62, 0x5d, 0xa9, 0x5c, 0xa3, 0xd7, 0x22, 0x65, 0x81, 0xa9, 0x2e,
	0xb2, 0xeb, 0x98, 0xbd, 0x55, 0xcc, 0x2a, 0x28, 0x32, 0x53, 0xc6, 0xb8, 0x75, 0xa0, 0x32, 0xc5,
	0xda, 0xfe, 0xab, 0x0e, 0x50, 0x0e, 0x50, 0x7d, 0x5b, 0x10, 0x29, 0x76, 0x9d, 0x78, 0x0a, 0xcd,
	0x24, 0x25, 0x01, 0x36, 0xe3, 0x94, 0x06, 0xfa, 0x12, 0x5e, 0x9a, 0xb9, 0xd1, 0x88, 0x49, 0xd6,
	0x8d, 0xf9, 0x4c, 0xd4, 0x14, 0x69, 0xc4, 0x5c, 0x20, 0xc5, 0x1a, 0xbd, 0x01, 0x24, 0x79, 0xa7,
	0x73, 0x16, 0x87, 0x38, 0x9d, 0xc6, 0x6c, 0x46, 0xa8, 0xd5, 0x90, 0x5f, 0x3c, 0x96, 0x91, 0xef,
	0x65, 0xe0, 0x46, 0xf8, 0xd1, 0x27, 0xd0, 0x53, 0x68, 0x3f, 0x5f, 0x15, 0xe0, 0xa6, 0x04, 0x1f,
	0xc9, 0xc0, 0x58, 0xf8, 0x15, 0xd6, 0x81, 0x93, 0x27, 0x2f, 0x26, 0xe1, 0x34, 0xa7, 0x9c, 0xc4,
	0xd3, 0x0c, 0x07, 0x8c, 0x86, 0x99, 0xd5, 0x1a, 0xd6, 0x2e, 0x0e, 0xdc, 0x9e, 0x0c, 0xdd, 0x8b,
	0xc8, 0x9d, 0x0a, 0x88, 0xc6, 0x02, 0x96, 0x53, 0x6e, 0xbd, 0x50, 0x8d, 0x49, 0xc3, 0xfe, 0x15,
	0xa0, 0xac, 0x1c, 0x75, 0xa1, 0x5e, 0xe8, 0xa2, 0x4e, 0x42, 0xf4, 0x11, 0x1c, 0x91, 0x10, 0x53,
	0x4e, 0xf8, 0x6a, 0x9a, 0xe4, 0xfe, 0x02, 0xaf, 0xe4, 0x58, 0x3a, 0x6e, 0xd7, 0xb8, 0x6f, 0xa5,
	0x57, 0x8c, 0x7b, 0xce, 0xb2, 0x62, 0xdc, 0x62, 0x6d, 0x4f, 0xe0, 0x95, 0x91, 0xc7, 0xd8, 0x8b,
	0x3d, 0x1a, 0xe0, 0xe2, 0x28, 0x95, 0x4a, 0xab, 0xfd, 0x27, 0xa5, 0x45, 0x60, 0x6d, 0x53, 0x69,
	0xb5, 0x5d, 0x42, 0xdb, 0xd7, 0x3e, 0xad, 0x37, 0x6b, 0x4b, 0x6f, 0x3a, 0xc9, 0x2d, 0x90, 0x7b,
	0x4e, 0xcd, 0x23, 0x1c, 0x56, 0xf1, 0x7b, 0x24, 0x72, 0x0e, 0x1d, 0xef, 0xc9, 0x23, 0xb1, 0xe7,
	0xc7, 0x46, 0x26, 0xa5, 0x03, 0xf5, 0xa1, 0x15, 0xa5, 0xec, 0x4f, 0x4c, 0xe5, 0x30, 0x1a, 0xae,
	0xb6, 0xec, 0xaf, 0x00, 0xca, 0xce, 0x04, 0x73, 0x4c, 0x96, 0x84, 0x4b, 0xe6, 0x86, 0xab, 0x0c,
	0x91, 0xcb, 0xa2, 0x28, 0xc3, 0x5c, 0xd3, 0x6a, 0xcb, 0xfe, 0x14, 0x4e, 0x7e, 0xc1, 0x29, 0x89,
	0x56, 0x6a, 0xaf, 0xcc, 0x18, 0x05, 0x89, 0x94, 0x88, 0x2e, 0x4f, 0x1a, 0xf6, 0x0f, 0xd0, 0x93,
	0x30, 0x75, 0x1e, 0x34, 0x74, 0xcf, 0x49, 0x92, 0x77, 0xc8, 0xbe, 0x93, 0x24, 0x83, 0xf6, 0x0d,
	0x1c, 0xdf, 0x79, 0x4f, 0x78, 0x1c, 0xb3, 0x60, 0xf1, 0x2f, 0x6c, 0xbe, 0xc0, 0x6c, 0xb1, 0xa9,
	0x4c, 0x15, 0xb4, 0xdf, 0xc0, 0x91, 0xd9, 0x49, 0x43, 0xf6, 0x2e, 0xb4, 0x95, 0xe8, 0x0b, 0xe9,
	0xbd, 0x90, 0xf6, 0x24, 0xb4, 0xbf, 0x86, 0xe3, 0x12, 0xbd, 0xe3, 0x76, 0xa9, 0x3d, 0x7b, 0xbb,
	0xbc, 0xfd, 0xbb, 0x01, 0xe0, 0x16, 0x41, 0xf4, 0x00, 0xdd, 0xf5, 0x3b, 0x17, 0x7d, 0x50, 0xcd,
	0xdd, 0x79, 0xeb, 0x0f, 0xec, 0xe7, 0x20, 0xba, 0xa4, 0xdf, 0xca, 0x32, 0x8d, 0x3c, 0xd1, 0x87,
	0xbb, 0xf2, 0x36, 0xce, 0xc1, 0xe0, 0xf5, 0xf3, 0x20, 0x4d, 0x7f, 0x0d, 0x87, 0xd5, 0xdd, 0x47,
	0xef, 0x57, 0xb3, 0x76, 0xe8, 0x62, 0xd0, 0x77, 0xd4, 0x03, 0xe7, 0x98, 0x07, 0xce, 0xb9, 0x12,
	0x0f, 0x1c, 0xfa, 0x56, 0x1f, 0x76, 0x75, 0xb9, 0xbe, 0xb7, 0x75, 0x7d, 0x55, 0xb7, 0x65, 0x2f,
	0xc9, 0x37, 0xd0, 0x29, 0xf4, 0x80, 0xce, 0xab, 0x1c, 0x9b, 0x32, 0xd9, 0x4b, 0x71, 0x05, 0x6d,
	0xd3, 0x2c, 0x3a, 0xdb, 0x35, 0x02, 0x43, 0x70, 0xbe, 0x3b, 0xa8, 0xe7, 0xf2, 0x13, 0x1c, 0x56,
	0xdf, 0x9f, 0xf5, 0xb9, 0xec, 0x78, 0xfd, 0x06, 0xc3, 0xfd, 0x00, 0x45, 0x39, 0xfe, 0xe2, 0xf1,
	0x72, 0x46, 0xf8, 0x3c, 0xf7, 0x9d, 0x80, 0x2d, 0x47, 0xc9, 0x82, 0x7f, 0x16, 0x78, 0xd9, 0x5c,
	0x2c, 0xc2, 0x51, 0x4c, 0xc5, 0x2f, 0x4d, 0x82, 0xd1, 0xd6, 0xff, 0x10, 0xbf, 0x25, 0x5d, 0x9f,
	0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x5d, 0x5c, 0x75, 0xa3, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReplicatorClient is the client API for Replicator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicatorClient interface {
	// Returns available token offers
	GetTokenOffers(ctx context.Context, in *GetTokenOffersRequest, opts ...grpc.CallOption) (*GetTokenOffersResponse, error)
	// Returns current token balances
	GetTokenBalances(ctx context.Context, in *GetTokenBalancesRequest, opts ...grpc.CallOption) (*GetTokenBalancesResponse, error)
	// Verifies a user permitions to issue a token. Returns exceptions if
	// passed user is not contained in issuer's db
	VerifyIssuer(ctx context.Context, in *VerifyIssuerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// IssueToken — Issue new token with given data. Request data equal to
	// token purchase data, because it is token offer.
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SaveBlock(ctx context.Context, in *SaveBlockRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	// GetTokenList — return list of issued token with infomation about
	// expiration time and fix price.
	GetTokenList(ctx context.Context, in *GetTokenListRequest, opts ...grpc.CallOption) (*GetTokenListResponse, error)
}

type replicatorClient struct {
	cc *grpc.ClientConn
}

func NewReplicatorClient(cc *grpc.ClientConn) ReplicatorClient {
	return &replicatorClient{cc}
}

func (c *replicatorClient) GetTokenOffers(ctx context.Context, in *GetTokenOffersRequest, opts ...grpc.CallOption) (*GetTokenOffersResponse, error) {
	out := new(GetTokenOffersResponse)
	err := c.cc.Invoke(ctx, "/replicator.Replicator/GetTokenOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicatorClient) GetTokenBalances(ctx context.Context, in *GetTokenBalancesRequest, opts ...grpc.CallOption) (*GetTokenBalancesResponse, error) {
	out := new(GetTokenBalancesResponse)
	err := c.cc.Invoke(ctx, "/replicator.Replicator/GetTokenBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicatorClient) VerifyIssuer(ctx context.Context, in *VerifyIssuerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/replicator.Replicator/VerifyIssuer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicatorClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/replicator.Replicator/IssueToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicatorClient) SaveBlock(ctx context.Context, in *SaveBlockRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/replicator.Replicator/SaveBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicatorClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/replicator.Replicator/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicatorClient) GetTokenList(ctx context.Context, in *GetTokenListRequest, opts ...grpc.CallOption) (*GetTokenListResponse, error) {
	out := new(GetTokenListResponse)
	err := c.cc.Invoke(ctx, "/replicator.Replicator/GetTokenList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicatorServer is the server API for Replicator service.
type ReplicatorServer interface {
	// Returns available token offers
	GetTokenOffers(context.Context, *GetTokenOffersRequest) (*GetTokenOffersResponse, error)
	// Returns current token balances
	GetTokenBalances(context.Context, *GetTokenBalancesRequest) (*GetTokenBalancesResponse, error)
	// Verifies a user permitions to issue a token. Returns exceptions if
	// passed user is not contained in issuer's db
	VerifyIssuer(context.Context, *VerifyIssuerRequest) (*empty.Empty, error)
	// IssueToken — Issue new token with given data. Request data equal to
	// token purchase data, because it is token offer.
	IssueToken(context.Context, *IssueTokenRequest) (*empty.Empty, error)
	SaveBlock(context.Context, *SaveBlockRequest) (*empty.Empty, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	// GetTokenList — return list of issued token with infomation about
	// expiration time and fix price.
	GetTokenList(context.Context, *GetTokenListRequest) (*GetTokenListResponse, error)
}

// UnimplementedReplicatorServer can be embedded to have forward compatible implementations.
type UnimplementedReplicatorServer struct {
}

func (*UnimplementedReplicatorServer) GetTokenOffers(ctx context.Context, req *GetTokenOffersRequest) (*GetTokenOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenOffers not implemented")
}
func (*UnimplementedReplicatorServer) GetTokenBalances(ctx context.Context, req *GetTokenBalancesRequest) (*GetTokenBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenBalances not implemented")
}
func (*UnimplementedReplicatorServer) VerifyIssuer(ctx context.Context, req *VerifyIssuerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyIssuer not implemented")
}
func (*UnimplementedReplicatorServer) IssueToken(ctx context.Context, req *IssueTokenRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueToken not implemented")
}
func (*UnimplementedReplicatorServer) SaveBlock(ctx context.Context, req *SaveBlockRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBlock not implemented")
}
func (*UnimplementedReplicatorServer) GetToken(ctx context.Context, req *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (*UnimplementedReplicatorServer) GetTokenList(ctx context.Context, req *GetTokenListRequest) (*GetTokenListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenList not implemented")
}

func RegisterReplicatorServer(s *grpc.Server, srv ReplicatorServer) {
	s.RegisterService(&_Replicator_serviceDesc, srv)
}

func _Replicator_GetTokenOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).GetTokenOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicator.Replicator/GetTokenOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).GetTokenOffers(ctx, req.(*GetTokenOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replicator_GetTokenBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).GetTokenBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicator.Replicator/GetTokenBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).GetTokenBalances(ctx, req.(*GetTokenBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replicator_VerifyIssuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyIssuerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).VerifyIssuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicator.Replicator/VerifyIssuer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).VerifyIssuer(ctx, req.(*VerifyIssuerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replicator_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicator.Replicator/IssueToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replicator_SaveBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).SaveBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicator.Replicator/SaveBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).SaveBlock(ctx, req.(*SaveBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replicator_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicator.Replicator/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replicator_GetTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).GetTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replicator.Replicator/GetTokenList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).GetTokenList(ctx, req.(*GetTokenListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replicator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "replicator.Replicator",
	HandlerType: (*ReplicatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTokenOffers",
			Handler:    _Replicator_GetTokenOffers_Handler,
		},
		{
			MethodName: "GetTokenBalances",
			Handler:    _Replicator_GetTokenBalances_Handler,
		},
		{
			MethodName: "VerifyIssuer",
			Handler:    _Replicator_VerifyIssuer_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _Replicator_IssueToken_Handler,
		},
		{
			MethodName: "SaveBlock",
			Handler:    _Replicator_SaveBlock_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _Replicator_GetToken_Handler,
		},
		{
			MethodName: "GetTokenList",
			Handler:    _Replicator_GetTokenList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/replicator/replicator.proto",
}
