// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/lock/lock.proto

package lock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Lock contain information about tokens and contract for transferring
type Lock struct {
	// count — number of sending tokens
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// owner — wallet addres of new owner of tokens
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// old_owner — owner of the wallet address to which tokens will be returned
	OldOwner string `protobuf:"bytes,3,opt,name=old_owner,json=oldOwner,proto3" json:"old_owner,omitempty"`
	// htlc — hash of contract
	Htlc string `protobuf:"bytes,4,opt,name=htlc,proto3" json:"htlc,omitempty"`
	// proof_count — lock expiration time in PKT blocks
	ProofCount int32 `protobuf:"varint,5,opt,name=proof_count,json=proofCount,proto3" json:"proof_count,omitempty"`
	// timeover_pkt — block height of PKT block when this lock will over
	TimeoverPkt int32 `protobuf:"varint,6,opt,name=timeover_pkt,json=timeoverPkt,proto3" json:"timeover_pkt,omitempty"`
	// creation_height — creation height in token blockchain
	CreationHeight uint64 `protobuf:"varint,7,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height,omitempty"`
	// signature generated with old owner private key
	Signature            string   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lock) Reset()         { *m = Lock{} }
func (m *Lock) String() string { return proto.CompactTextString(m) }
func (*Lock) ProtoMessage()    {}
func (*Lock) Descriptor() ([]byte, []int) {
	return fileDescriptor_d340bab4d79d59c9, []int{0}
}

func (m *Lock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lock.Unmarshal(m, b)
}
func (m *Lock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lock.Marshal(b, m, deterministic)
}
func (m *Lock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lock.Merge(m, src)
}
func (m *Lock) XXX_Size() int {
	return xxx_messageInfo_Lock.Size(m)
}
func (m *Lock) XXX_DiscardUnknown() {
	xxx_messageInfo_Lock.DiscardUnknown(m)
}

var xxx_messageInfo_Lock proto.InternalMessageInfo

func (m *Lock) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Lock) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Lock) GetOldOwner() string {
	if m != nil {
		return m.OldOwner
	}
	return ""
}

func (m *Lock) GetHtlc() string {
	if m != nil {
		return m.Htlc
	}
	return ""
}

func (m *Lock) GetProofCount() int32 {
	if m != nil {
		return m.ProofCount
	}
	return 0
}

func (m *Lock) GetTimeoverPkt() int32 {
	if m != nil {
		return m.TimeoverPkt
	}
	return 0
}

func (m *Lock) GetCreationHeight() uint64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *Lock) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*Lock)(nil), "lock.Lock")
}

func init() { proto.RegisterFile("protos/lock/lock.proto", fileDescriptor_d340bab4d79d59c9) }

var fileDescriptor_d340bab4d79d59c9 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x89, 0xdb, 0xae, 0xdb, 0x59, 0x51, 0x08, 0x22, 0x01, 0x05, 0xab, 0x17, 0x7b, 0xb1,
	0x15, 0xfc, 0x07, 0x7a, 0xf1, 0x20, 0x28, 0x3d, 0x7a, 0x29, 0xdd, 0x34, 0xb6, 0xa5, 0xd9, 0x4c,
	0x48, 0xa7, 0xfa, 0xaf, 0xfd, 0x0d, 0xd2, 0x29, 0x8b, 0x1e, 0x12, 0xde, 0xfb, 0xde, 0xc0, 0x1b,
	0x06, 0x2e, 0x7c, 0x40, 0xc2, 0xb1, 0xb0, 0xa8, 0x07, 0xfe, 0x72, 0x06, 0x32, 0x9a, 0xf5, 0xed,
	0x8f, 0x80, 0xe8, 0x15, 0xf5, 0x20, 0xcf, 0x21, 0xd6, 0x38, 0x39, 0x52, 0x22, 0x15, 0xd9, 0xaa,
	0x5c, 0xcc, 0x4c, 0xf1, 0xdb, 0x99, 0xa0, 0x8e, 0x52, 0x91, 0x25, 0xe5, 0x62, 0xe4, 0x25, 0x24,
	0x68, 0x9b, 0x6a, 0x49, 0x56, 0x9c, 0x6c, 0xd0, 0x36, 0x6f, 0x1c, 0x4a, 0x88, 0x3a, 0xb2, 0x5a,
	0x45, 0xcc, 0x59, 0xcb, 0x6b, 0xd8, 0xfa, 0x80, 0xf8, 0x59, 0x2d, 0x15, 0x71, 0x2a, 0xb2, 0xb8,
	0x04, 0x46, 0xcf, 0xdc, 0x73, 0x03, 0x27, 0xd4, 0xef, 0x0d, 0x7e, 0x99, 0x50, 0xf9, 0x81, 0xd4,
	0x9a, 0x27, 0xb6, 0x07, 0xf6, 0x3e, 0x90, 0xbc, 0x83, 0x33, 0x1d, 0x4c, 0x4d, 0x3d, 0xba, 0xaa,
	0x33, 0x7d, 0xdb, 0x91, 0x3a, 0x4e, 0x45, 0x16, 0x95, 0xa7, 0x07, 0xfc, 0xc2, 0x54, 0x5e, 0x41,
	0x32, 0xf6, 0xad, 0xab, 0x69, 0x0a, 0x46, 0x6d, 0x78, 0x8b, 0x3f, 0xf0, 0xf4, 0xf0, 0x91, 0xb7,
	0x3d, 0x75, 0xd3, 0x2e, 0xd7, 0xb8, 0x2f, 0xfc, 0x40, 0xf7, 0xba, 0x1e, 0xbb, 0x59, 0x34, 0x85,
	0x75, 0xf3, 0x0b, 0x5e, 0x17, 0xff, 0x6e, 0xb6, 0x5b, 0xb3, 0x79, 0xfc, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xfa, 0x55, 0xdd, 0x86, 0x49, 0x01, 0x00, 0x00,
}
