// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/discredit/discredit.proto

package discredit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	DB "github.com/pkt-cash/pktd/lnd/lnrpc/protos/DB"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DuplicateBlock 2 identical blocks were generated (Updated the structure)
type DuplicateBlock struct {
	// first_block_header — copied block
	FirstBlockHeader *DB.Block `protobuf:"bytes,1,opt,name=first_block_header,json=firstBlockHeader,proto3" json:"first_block_header,omitempty"`
	// second_block_header — block copy
	SecondBlockHeader    *DB.Block `protobuf:"bytes,2,opt,name=second_block_header,json=secondBlockHeader,proto3" json:"second_block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DuplicateBlock) Reset()         { *m = DuplicateBlock{} }
func (m *DuplicateBlock) String() string { return proto.CompactTextString(m) }
func (*DuplicateBlock) ProtoMessage()    {}
func (*DuplicateBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d7938a26e59d63d, []int{0}
}

func (m *DuplicateBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateBlock.Unmarshal(m, b)
}
func (m *DuplicateBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateBlock.Marshal(b, m, deterministic)
}
func (m *DuplicateBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateBlock.Merge(m, src)
}
func (m *DuplicateBlock) XXX_Size() int {
	return xxx_messageInfo_DuplicateBlock.Size(m)
}
func (m *DuplicateBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateBlock.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateBlock proto.InternalMessageInfo

func (m *DuplicateBlock) GetFirstBlockHeader() *DB.Block {
	if m != nil {
		return m.FirstBlockHeader
	}
	return nil
}

func (m *DuplicateBlock) GetSecondBlockHeader() *DB.Block {
	if m != nil {
		return m.SecondBlockHeader
	}
	return nil
}

// DenialService the issuer accepts a lock_tokens request from a sender but
// then ignores the transfer_tokens request from the recipient
type DenialService struct {
	// lock — hash of ignored lock
	Lock string `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	// htlc_secret — htlc genereted issuer
	HtlcSecret string `protobuf:"bytes,2,opt,name=htlc_secret,json=htlcSecret,proto3" json:"htlc_secret,omitempty"`
	// proof_mercle_branch — proof from PKT blockchain
	ProofMercleBranch string `protobuf:"bytes,3,opt,name=proof_mercle_branch,json=proofMercleBranch,proto3" json:"proof_mercle_branch,omitempty"`
	// creation_height — height of the block on create lock
	CreationHeight uint64 `protobuf:"varint,4,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height,omitempty"`
	// lock_expire — pkt block on which has expired lock
	LockExpire           uint64   `protobuf:"varint,5,opt,name=lock_expire,json=lockExpire,proto3" json:"lock_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenialService) Reset()         { *m = DenialService{} }
func (m *DenialService) String() string { return proto.CompactTextString(m) }
func (*DenialService) ProtoMessage()    {}
func (*DenialService) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d7938a26e59d63d, []int{1}
}

func (m *DenialService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenialService.Unmarshal(m, b)
}
func (m *DenialService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenialService.Marshal(b, m, deterministic)
}
func (m *DenialService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenialService.Merge(m, src)
}
func (m *DenialService) XXX_Size() int {
	return xxx_messageInfo_DenialService.Size(m)
}
func (m *DenialService) XXX_DiscardUnknown() {
	xxx_messageInfo_DenialService.DiscardUnknown(m)
}

var xxx_messageInfo_DenialService proto.InternalMessageInfo

func (m *DenialService) GetLock() string {
	if m != nil {
		return m.Lock
	}
	return ""
}

func (m *DenialService) GetHtlcSecret() string {
	if m != nil {
		return m.HtlcSecret
	}
	return ""
}

func (m *DenialService) GetProofMercleBranch() string {
	if m != nil {
		return m.ProofMercleBranch
	}
	return ""
}

func (m *DenialService) GetCreationHeight() uint64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *DenialService) GetLockExpire() uint64 {
	if m != nil {
		return m.LockExpire
	}
	return 0
}

func init() {
	proto.RegisterType((*DuplicateBlock)(nil), "discredit.DuplicateBlock")
	proto.RegisterType((*DenialService)(nil), "discredit.DenialService")
}

func init() { proto.RegisterFile("protos/discredit/discredit.proto", fileDescriptor_4d7938a26e59d63d) }

var fileDescriptor_4d7938a26e59d63d = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0xc9, 0xf7, 0x55, 0xa1, 0x53, 0xac, 0x76, 0xba, 0x30, 0xb8, 0xb1, 0x74, 0x63, 0x37,
	0x26, 0x60, 0x71, 0x27, 0x2e, 0x42, 0x85, 0x6e, 0xdc, 0xa4, 0x3b, 0x37, 0x21, 0x39, 0x39, 0xed,
	0x0c, 0x49, 0x33, 0xc3, 0x99, 0xa9, 0x78, 0x15, 0x5e, 0x92, 0xd7, 0x26, 0x73, 0x6a, 0xfd, 0xc3,
	0x45, 0xe0, 0xcd, 0xf3, 0x3e, 0x6f, 0x7e, 0x18, 0x31, 0xb1, 0x64, 0xbc, 0x71, 0x69, 0xad, 0x1d,
	0x10, 0xd6, 0xda, 0x7f, 0xa5, 0x84, 0x2b, 0xd9, 0xff, 0x04, 0x17, 0xe7, 0x1f, 0xf2, 0x22, 0x4b,
	0xbd, 0x69, 0xb0, 0xab, 0xab, 0xbd, 0x33, 0x7d, 0x8d, 0xc4, 0x70, 0xb1, 0xb3, 0xad, 0x86, 0xd2,
	0x63, 0xd6, 0x1a, 0x68, 0xe4, 0x9d, 0x90, 0x6b, 0x4d, 0xce, 0x17, 0x55, 0xb8, 0x2d, 0x14, 0x96,
	0x35, 0x52, 0x1c, 0x4d, 0xa2, 0xd9, 0xe0, 0x66, 0x98, 0x1c, 0xe6, 0xec, 0xe6, 0x67, 0x6c, 0x72,
	0x5e, 0xb2, 0x27, 0xef, 0xc5, 0xd8, 0x21, 0x98, 0xae, 0xfe, 0x39, 0xff, 0xf7, 0xe7, 0x7c, 0xb4,
	0x57, 0xbf, 0xed, 0xa7, 0x6f, 0x91, 0x38, 0x59, 0x60, 0xa7, 0xcb, 0x76, 0x85, 0xf4, 0xac, 0x01,
	0xa5, 0x14, 0xbd, 0xd0, 0xf3, 0x17, 0xf4, 0x73, 0xce, 0xf2, 0x52, 0x0c, 0x94, 0x6f, 0xa1, 0x70,
	0x08, 0x84, 0x9e, 0x9f, 0xde, 0xcf, 0x45, 0x40, 0x2b, 0x26, 0x32, 0x11, 0x63, 0x4b, 0xc6, 0xac,
	0x8b, 0x2d, 0x12, 0xb4, 0x58, 0x54, 0x54, 0x76, 0xa0, 0xe2, 0xff, 0x2c, 0x8e, 0xb8, 0x7a, 0xe4,
	0x26, 0xe3, 0x42, 0x5e, 0x89, 0x53, 0x20, 0x2c, 0xbd, 0x36, 0x5d, 0xa1, 0x50, 0x6f, 0x94, 0x8f,
	0x7b, 0x93, 0x68, 0xd6, 0xcb, 0x87, 0x07, 0xbc, 0x64, 0x1a, 0xde, 0xcc, 0xff, 0x85, 0x2f, 0x56,
	0x13, 0xc6, 0x47, 0x2c, 0x89, 0x80, 0x1e, 0x98, 0x64, 0xb7, 0x4f, 0xf3, 0x8d, 0xf6, 0x6a, 0x57,
	0x25, 0x60, 0xb6, 0xa9, 0x6d, 0xfc, 0x35, 0x94, 0x4e, 0x85, 0x50, 0xa7, 0x6d, 0x17, 0x2e, 0xb2,
	0x90, 0xfe, 0x3e, 0xbc, 0xea, 0x98, 0xc9, 0xfc, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xf7, 0x69,
	0x4d, 0xd7, 0x01, 0x00, 0x00,
}
